### ISSUE TITLE
Gnome Panel should be respected

### ISSUE THREAD

**Issue by ChrisLauinger77** [Leleat/Tiling-Assistant#350] opened 2024-06-08 11:02 UTC
**Describe the bug**
The gnome panel is not respected and the tiled windows overlap them.
Did not find an option - tried also layout but seems it cannot be done to respect and not overlap the top bar.
Am I missing something or is this currently not possible ?

I am a fan of this extension ! Great work - loving how it improves my workflow :)

**Steps To Reproduce**
just use the tiliing and observe that the tiled window is always overlapping the gnome panel.
I want to gnome panel still visibly after the tiling happened.

**System Info:**
 - Distro (incl. version): debian trixie (with some packages from exp)
 - GNOME Shell version: 46
 - Extension version and from where (e. g. EGO, `main` branch...): 46 / debian package
 - Wayland

https://gist.github.com/ChrisLauinger77/ac3f8a7cf89c1499688617bbad1d0cdb

**Comment by ChrisLauinger77** [comment] 2024-06-08 11:06
I found the option - the 1st page of the settings can be scrolled and I was blind to see it :(
Sorry

**Comment by Leleat** [comment] 2024-06-09 18:23
>  The gnome panel is not respected and the tiled windows overlap them.

Tbh, I am a bit confused. 

The "GNOME panel" should never be overlapped by tiled windows (at most tiled windows may touch the panel). There is also no setting to enable or disable that behavior. The only setting that would be somewhat related are the 'gaps' settings. But if tiled windows are overlapping the panel, those settings would only be a workaround... So maybe there is a bug here. To determine, if this is a bug, can you please provide more info?

First, what do you mean with the 'gnome panel'? Do you mean the panel with the date menu, system menu, quick settings etc? Or do you have another panel (enabled via a different extension)?

**Comment by ChrisLauinger77** [comment] 2024-06-09 18:29
Yes I mean the top panel with the date etc
I found the setting where I can which solved my „issue“ can add a screenshot tomorrow.

**Comment by Leleat** [comment] 2024-06-09 18:34
> Yes I mean the top panel with the date etc

Yeah, then that may be a bug. Here is a video showcasing how it should work https://github.com/Leleat/Tiling-Assistant/wiki/Window-Grab-Modes#edge-tiling

**Comment by ChrisLauinger77** [comment] 2024-06-09 18:45
![grafik](https://github.com/Leleat/Tiling-Assistant/assets/3518684/a76075eb-eb46-4eaf-94a5-f1b8dca28727)
This is the setting which fixed the behaviour for me. Maybe its because I also use AutoHideTopBar extension.
The 30 px from top border made it for me as expected

**Comment by Leleat** [comment] 2024-06-09 18:58
>  Maybe its because I also use AutoHideTopBar extension.

Yeah, that's the cause of the issue.

While I don't know which extension AutoHideTopBar exactly refers to, but I imagine that extension makes the panel no longer 'affect struts', i. e. the panel will no longer be taken into account when calculating the available work area.

Off the top of my head, I don't think the extension will cause any other conflicts. So the gaps ('Zwischenräume') settings should indeed be a good workaround/solution to the problem. So I am closing the issue again.

**Closed by Leleat** 2024-06-09 18:58 UTC
Labels: bug, Needs info / steps to reproduce

**Comment by ChrisLauinger77** [comment] 2024-06-09 19:58
https://packages.debian.org/sid/gnome-shell-extension-autohidetopbar

**Comment by Leleat** [comment] 2024-06-09 20:27
https://salsa.debian.org/debian/gnome-shell-extension-autohidetopbar/-/blob/master/panelVisibilityManager.js#L56

With a quick grep, it's as I suspected: the extension removes the `affectsStruts` effect of the panel which means your workspace is bigger but also that windows can extend under the panel. So there is nothing for me to fix here (and I'd say the other extension also works as expected).
