### ISSUE TITLE
Gnome Terminal tiled outside of the display?

### ISSUE THREAD

**Issue by OrkanSaklan** [Leleat/Tiling-Assistant#71] opened 2021-05-05 09:55 UTC
**Describe the bug**
Gnome Terminal shows a gap at the bottom. I'm on xorg. Looks more like a serious bug, since I had to restart the extension to continue my work. But I don't remember what broke after playing around with the terminal.

**Steps To Reproduce**
Just tile gnome-terminal to reproduce.

**Screenshots/-captures**
https://imgur.com/a/1znvvG5

**System Info:**
 - Distro (incl. version): Fedora
 - GNOME version: 40

 - Extensions version: 19
 - XOrg/Wayland: X11

**Journalctl logs**

**Additional context**

**Comment by Leleat** [comment] 2021-05-05 10:02
> Looks more like a serious bug, since I had to restart the extension to continue my work.

Why did you need to restart the extension?

The gap itself is not a bug of my extension (unless it was reallly big). A few pixels is expected with GNOME Terminal because it can only resize in full columns/rows. Try resizing the Terminal and you'll notice that. It's a limitation of what a GNOME extension can do.

**Comment by Leleat** [comment] 2021-05-05 10:05
> Why did you need to restart the extension?

Did you have any other issues except the gap?

**Comment by OrkanSaklan** [comment] 2021-05-05 10:28
> > Why did you need to restart the extension?
> 
> Did you have any other issues except the small gap?

OK, wait I just managed to face that problem again. I don't know how I did that, but I see that If I want to tile the gnome-terminal at the bottom corner to make a 1/4 window it tiles it out of the display. You only see a tiny part of the header of the window. Looks like that appears only with gnome-terminal. I dont know how to reproduce that though. Confusing behaivor.

**Comment by Leleat** [comment] 2021-05-05 10:31
> I don't know how I did that, but I see that If I want to tile the gnome-terminal at the bottom corner to make a 1/4 window it tiles it out of the display

That is a bug then. If you can reproduce it, please post the info here, so that I can try to do it. I tried playing around with the Terminal but nothing happened.

**Comment by OrkanSaklan** [comment] 2021-05-05 10:34
I'll try to make a video, I think I know what it is.

**Comment by OrkanSaklan** [comment] 2021-05-05 10:37
Because of the gap of the terminal, you can resize it from the bottom. If you have 4x4 tiling, and use the terminal at the bottom left or right you can resize it, which will also resize the window on the opposite site. Then you can tile the terminal window out of the display. Hope I could explain that well. Otherwise I will try to simulate it in a video.

**Comment by Leleat** [comment] 2021-05-05 10:44
> Then you can tile the terminal window out of the display. Hope I could explain that well. Otherwise I will try to simulate it in a video.

Do you use multiple monitors? Please do post a video. I tried to resize the Terminal with a 2x2 Grid  in the bottom row but the result is as expected.

> Because of the gap of the terminal, you can resize it from the bottom

That unfortunately is always the case. All tiling **extensions** are just a kinda _hacky_. Proper tiling needs to be implemented in Mutter, which a GNOME extension has no access to. So I can't stop you from resizing on the wrong side...

**Comment by OrkanSaklan** [comment] 2021-05-05 10:52
https://user-images.githubusercontent.com/16062633/117130540-80ab1380-ada0-11eb-9ad5-ee278e204b40.mp4



> That unfortunately is always the case. All tiling **extensions** are just a kinda _hacky_. Proper tiling needs to be implemented in Mutter, which a GNOME extension has no access to. So I can't stop you from resizing on the wrong side... (this isn't limited to the terminal but applies to all windows)

Then I think this is not fixable, right?

**Comment by OrkanSaklan** [comment] 2021-05-05 10:59
> Do you use multiple monitors? Please do post a video. I tried to resize the Terminal with a 2x2 Grid in the bottom row but the result is as expected / not buggy.
> 
> >
I forgot the answer that question. Yes, I use two monitors.

Btw. not to this topic, but if I drag a window to the top bar makes it fullscreen but after a few seconds it turns to a stretched window. I think that is mean to happen, but is it possible to disable that feature? Or is it planned to configure this behavior in future? Thanks in advance for your reply.

**Comment by Leleat** [comment] 2021-05-05 11:16
> Then I think this is not fixable, right?

Not really. I can't stop you from resizing a window. But I also don't necessarily consider what you've shown me a bug but a feature ;)

To go into detail:

My extension isn't meant to be limited to quarter tiling (i. e. a 2x2 grid). Quarter tiling is just the default behaviour, if you drag the window around on the screen edges. If you drag a window to the screen corners, it will dynamcially look for the rectangle in that corner based on the tiled windows/free screen rectangles around. For example here:

![output](https://user-images.githubusercontent.com/53054301/117132694-b517d300-ad92-11eb-935c-e08dc3580248.gif)

I have 3 windows in the left column. So if I drag another window to the bottom right corner, it won't fill 1/4 of the screen but looks for the bottom right rectangle. Same goes for your video. `Nautilus` splits the bottom right quarter into smaller rectangles for more complex layouts.

**Comment by Leleat** [comment] 2021-05-05 11:18
> think that is mean to happen, but is it possible to disable that feature

Yes, that's intentional. There is a timer in the 'Hidden Settings'. You can increase it, if you it's too short for you. If it still bugs you, I can add a setting to disable it. But try increasing the timer first.

![Screenshot from 2021-05-05 13-17-17](https://user-images.githubusercontent.com/53054301/117133208-7cc4c480-ad93-11eb-903d-ca29d781fb1a.png)

**Comment by Leleat** [comment] 2021-05-05 11:27
A feature, which might help you create layouts is holding `Ctrl` when dragging windows around. You can 'split' tiled windows with it or occupy arbitrary free screen rectangles. The keyboard shortcut `Auto-tile` is also useful. It will try to expand the tiled window to fill the available space. Here is an example of both:

![output](https://user-images.githubusercontent.com/53054301/117133954-75ea8180-ad94-11eb-8d20-525cf98374c8.gif)

Anay way, closing this again as I don't consider it a bug as I mentioned or if you want to call it a bug, it's not fixable as an GNOME extension...

**Comment by OrkanSaklan** [comment] 2021-05-05 11:27
Oh, OK. I thought it was a bug, because I didn't know that your extension doesnt stop at 2x2. Good to know.

Oh, you literally hided that menu entry "hidden settings". I didn't know that it existed in the first place :D

Thanks, I'll increase the number then. 

I will close this issue then, and many thanks for the head up.

**Closed by Leleat** 2021-05-05 11:27 UTC
Labels: Needs STR, bug
