### ISSUE TITLE
Windows that change size may extend off the screen

### ISSUE THREAD

**Issue by chrisirwin** [Leleat/Tiling-Assistant#65] opened 2021-04-12 23:29 UTC
**Describe the bug**

Windows that change their own size (eg: Embiggening when tabs are made visible) may extend beyond the edge of tile boundry, possibly off screen

**Steps To Reproduce**

1. Open Gnome Terminal (tab bar is not visible)
2. Tile to a side
3. Open a new tab (tab bar becomes visible)
4. Bottom of terminal now off-screen

**Screenshots/-captures**

Window tiled to right with text typed on the bottom line for visibility:

![Tiled-on-screen](https://user-images.githubusercontent.com/6145931/114474812-02a28500-9bc5-11eb-91e2-c886b6703415.png)

After creating a new tab, the same terminal with the same text typed, which now extends beyond the bottom of the screen:

![Tiled-off-screen](https://user-images.githubusercontent.com/6145931/114474822-059d7580-9bc5-11eb-978a-8a259f7cd8af.png)

**System Info:**
 - Distro (incl. version): Fedora 34 Beta (currently up to date as of issue creation time)
 - GNOME version: 40.0.0
 - Extensions version: 15
 - XOrg/Wayland: Wayland

**Journalctl logs**
No journal entries when reproducing

**Additional context**

Does not occur with maximize (I expect this is still standard maximize as the gaps also don't apply)

Does not occur with Gnome's native window split (i.e., with this extension disabled)

Does occur with regular tiles -- gnome terminal will overlap other tiled windows, for example. Running off the bottom of the screen is a more visible problem.

**Comment by Leleat** [comment] 2021-04-12 23:53
> XOrg/Wayland: Wayland

Seems to be limited to Wayland. Can only reproduce it there (with gnome 3.38).

> Does not occur with maximize (I expect this is still standard maximize as the gaps also don't apply)

> Does not occur with Gnome's native window split (i.e., with this extension disabled)

Yes, I use gnome's `maximize` for the full maximize (which will 'block' resizing). For all other 'tiling' states I am just faking it by moving/resizing the window to the correct location. So the window isn't in a special (mutter) state (unlike gnome's native tiling), which means windows can resize freely.

Not sure, if there is something I can do about as an extension. Did you try other tiling extensions and know that they work without this issue? Maybe I could take a look at those

**Comment by Leleat** [comment] 2021-04-12 23:59
Can you reproduce it with any other apps?

I tried to reproduce it with Nautilus but it didn't happed there (although Nautilus doesn't open the new tab in the foreground, so it isn't exact same thing).

**Comment by chrisirwin** [comment] 2021-04-13 00:53
> Did you try other tiling extensions and know that they work without this issue? Maybe I could take a look at those

No, not much is ported to Gnome 40 yet.

> Can you reproduce it with any other apps?

Nothing I can think of currently -- Apps like nautilus, gedit, and epiphany don't adjust window size when opening tabs. Other apps (firefox) have tabs enabled all the time. I can't think of any other apps that change their own window sizes at the moment.

**Comment by Leleat** [comment] 2021-07-30 19:06
This behaviour ("auto-resizing") seems to be rather uncommon and may not even be intentional for GNOME Terminal since I've seen some (related?) open issues about it on gitlab.

I've also already put it in the "known issues/limitations" issue, so I am closing this here as there is probably nothing I can do about it as a GNOME Shell extension.

**Closed by Leleat** 2021-07-30 19:06 UTC
Labels: Wayland, bug, help needed
