### ISSUE TITLE
Overlay appears when focusing second display after resizing

### ISSUE THREAD

**Issue by vsxed** [Leleat/Tiling-Assistant#116] opened 2021-11-16 08:05 UTC
Overlay appears when focusing second display after resizing

---

See attached video.

Transcription:
- Have two windows, one on each displays
- size the first window on the first display via Tiling Assistant
- click on the second window on the second display

**System Info:**
 - Distro (incl. version): Ubuntu 21.10 x86_64 
 - GNOME (Shell) version: GNOME 40.5 
 - Extension version: v27
 - XOrg/Wayland: XOrg
 - Resolution: 3440x1440, 3440x1440 (both are a LG 34UC99-W)

**Journalctl logs**
```shell
➜  ~ journalctl -fo cat /usr/bin/gnome-shell
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Error in size change accounting.
JS ERROR: TypeError: AltTab.AppSwitcher is undefined
_addIcon@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingPopup.js:446:9
_init@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingPopup.js:367:22
_init@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingPopup.js:50:30
tryOpeningTilingPopup@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/utility.js:714:23
tile@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/utility.js:633:33
_onMoveFinished@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/moveHandler.js:217:14
TilingMoveHandler/g2Id<@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/moveHandler.js:34:22

Error in size change accounting.
JS ERROR: TypeError: AltTab.AppSwitcher is undefined
_addIcon@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingPopup.js:446:9
_init@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingPopup.js:367:22
_init@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingPopup.js:50:30
tryOpeningTilingPopup@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/utility.js:714:23
tile@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/utility.js:633:33
_onMoveFinished@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/moveHandler.js:217:14
TilingMoveHandler/g2Id<@/home/eduard/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/moveHandler.js:34:22

Error in size change accounting.
```

**List of other extensions**
For the Video: Other extensions are enabled, possibly way too much to list them here, lol.
For the Log: Only Tiling Assistant enabled. Same issue occurs like in the screen capture, despite having all other extensions turned off.

**Screenshots/-captures**

https://user-images.githubusercontent.com/1070998/141945065-4836c9ea-1ff8-4baf-b88f-0e3298f543dc.mp4

**Comment by vsxed** [comment] 2021-11-16 08:19
After some more investigation, i managed to figure out that this issue only happens after waking the device up.
If this issue happens and i log out and log in back, the issue does not occur.

**Comment by Leleat** [comment] 2021-11-17 15:33
Thanks for the report.

I am pretty sure, I know what's going on here. I'll fix it soon-ish (this week hopefully).

**Comment by Leleat** [comment] 2021-11-20 20:23
> I am pretty sure, I know what's going on here. I'll fix it soon-ish (this week hopefully).

Scratch that. My initial gut feeling was wrong... I can't even reproduce this problem. I tried the STR with my laptop (Fedora with GNOME Shell 40.5) and with Ubuntu 21.10 in a VM (in this case only with 1 monitor). Some questions:

1. Are 2 monitors actually needed to trigger this or is only locking the screen necessary (like you you mentioned in the edited 2. comment)? Could you give me an updated STR?

> **List of other extensions**
> For the Video: Other extensions are enabled, possibly way too much to list them here, lol.
> For the Log: Only Tiling Assistant enabled. Same issue occurs like in the screen capture, despite having all other extensions turned off.

2. Did you trigger/encounter the bug before testing with all other extensions disabled? I. e. can you trigger the bug **after** disabling all other extensions **and** reloading GNOME Shell (`Alt + F2` -> enter `r`)?

**Comment by vsxed** [comment] 2021-11-20 20:55
Hey!

1. This issue is also reproducable with only 1 monitor attached. Sometimes, the issue is not visible at the first try, because it _could_ appear behind a window (see the screenshot: this little grey pixels are the overlay between 2 windows)

![image](https://user-images.githubusercontent.com/1070998/142740523-be944c47-8b52-4404-b5f1-6443192c63bf.png)


The error message appears to be still the same though (same reference, same file, same lines)

2. Seems like another extension is the issue. After restarting the shell *and* having all other extensions turned off (except for tiling assistant), it seems to work now.

Will investigate and see which extension it the bad guy.

Thanks for your help so far! Human error, omg.

**Comment by vsxed** [comment] 2021-11-20 21:03
But i think you can close this for now :) As soon as i find out who's the bad guy, i will add the information here.

**Comment by Leleat** [comment] 2021-11-20 21:14
Alright, thanks for the heads up, closing then.

To make your search easier for the conflicting extension:

> AltTab.AppSwitcher is undefined

This is refers to GNOME's native AltTab popup because I use it for my own Tiling Popup. So any extension, which might modify it, could cause the conflict.

**Closed by Leleat** 2021-11-20 21:14 UTC
Labels: bug
