### ISSUE TITLE
Tiling selection gets frozen unable to exit

### ISSUE THREAD

**Issue by linoshkmalayil** [Leleat/Tiling-Assistant#373] opened 2024-10-02 18:03 UTC
**Describe the bug**
When I try to tile windows and pan windows to any area, the selection for the remainder space does exit after I select window.
[Screencast From 2024-10-02 23-15-51.webm](https://github.com/user-attachments/assets/ef91b5f8-9253-4133-9d24-af45c40bb0ac)
This issue was introduced in GNOME 47, the extension worked perfectly in GNOME 46.

**Steps To Reproduce**
1. Open any two windows
2. Tile one window to one side
3. Select window for the remaining area.

**System Info:**
 - Distro (incl. version): Arch Linux (Kernel 6.11.1-arch1-1, systemd 256.6-1-arch)
 - GNOME Shell version: 47
 - Extension version and from where (e. g. EGO, `main` branch...): EGO
 - XOrg/Wayland: Wayland

**Journalctl logs**

```
Error in size change accounting.
JS ERROR: TypeError: this._timeoutIds is undefined
_delayedDestroy@file:///home/linosh/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1102:13
fadeAndDestroy@file:///home/linosh/.local/share/gnome-shell/extensions/advanced-alt-tab@G-dH.github.com/src/windowSwitcherPopup.js:1097:18
fadeAndDestroy@file:///home/linosh/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingPopup.js:271:15
_finish@resource:///org/gnome/shell/ui/switcherPopup.js:339:14
_finish@file:///home/linosh/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/src/extension/tilingPopup.js:257:55
vfunc_key_press_event@resource:///org/gnome/shell/ui/switcherPopup.js:207:18
@resource:///org/gnome/shell/ui/init.js:21:20

Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
Old animationInfo removed from actor [0x58a8397321a0 MetaWindowActorWayland]
Error in size change accounting.
```

**Comment by Leleat** [comment] 2024-10-02 19:05
I can't seem to reproduce this in Fedora Rawhide. Based on the log it looks like a conflict between Tiling Assistant and AATWS but even with both extensions installed I can't reproduce this bug. What other extensions do you have installed. Please also include their versions here.

**Comment by linoshkmalayil** [comment] 2024-10-03 08:58
Disabling AATWS fixes the issue.
So the conflict seems to be between these two.

But even still when I check the journalctl logs I see
```
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
```
For every tiling action I take.

I tried with all other extensions disabled and only with AATWS and Tiling Assistant and it too produced the bug.

However these are the extensions I use and installed:
AATWS - github commit: 96ea34737423ac2e76e9a532e698847f5fa00475
BlurMyShell - EGO
Dash to Dock - EGO
Desktop Icons NG - gitlab commit: c6dbd6589f525c053ac4a0027fb9feb4e5056bdc
GNOME 4x UI Improvements - EGO
GSConnect - github commit: fb1b30870a7b198bf9eef178fd1e83a07d6b1b9b
Lock Keys (kazimieras.vaina) - EGO
Tiling Assistant - EGO
Transparent Topbar (Adjustable Transparency) (Gonzague) - EGO

These extensions where built-in when I installed GNOME (all except User Themes are disabled)
Apps Menu
Auto Move Windows
Launch New Instance 
Light Style
Native Window Placement
Places Status Indicator
Removable Drive Menu
Screenshot Window Sizer
Status Icons
System Monitor
User Themes (This is the only one I have enabled)
Window List
windowNavigator
Workspace Indicator

**Comment by Leleat** [comment] 2024-10-03 09:17
> Error in size change accounting.

That error happens because Tiling Assistant misuses GNOME's window animations. If you disable the animations in Tiling Assistant, that message will disappear. But that error has been there since probably day-1 of Tiling Assistant and I've never actually noticed any side effects. So I never bothered to get rid of it since the only way to fix it is to write my own animations...

Back to this issue, I only tested AATWS from EGO and there weren't any conflicts. I'll see if I can reproduce this with that commit.

**Comment by linoshkmalayil** [comment] 2024-10-03 13:28
AATWS in EGO didn't run for me because it was incompatible with GNOME 47 (I didn't test adding 47 to the metadata.json) so I picked the latest version on github.

**Comment by Leleat** [comment] 2024-10-04 08:50
> AATWS in EGO didn't run for me because it was incompatible with GNOME 47 (I didn't test adding 47 to the metadata.json) 

Ah, I see. I only tested the EGO version by adding `47` to the `metadata.json`. But I am not a AATWS user, so I don't know if the extension actually works properly by doing that... I'll try looking at the `main` branch

**Comment by linoshkmalayil** [comment] 2024-10-11 17:55
Any update on this?

**Comment by Leleat** [comment] 2024-10-13 13:31
Didn't have the time to take a look at it yet. I'll try to do it next weekend.

**Comment by G-dH** [comment] 2024-10-16 15:19
@linoshkmalayil Fixed in AATWS, try to update from the `main` branch.

**Comment by Leleat** [comment] 2024-10-16 15:47
@G-dH Thanks for the compatibility patch on your side :+1:. So I am closing this issue.

**Closed by Leleat** 2024-10-16 15:47 UTC
Labels: bug

**Comment by linoshkmalayil** [comment] 2024-10-16 18:17
Tested commit: [AATWS-59a69ec](https://github.com/G-dH/advanced-alttab-window-switcher/commit/59a69eca30171c2a2d0b03e6a779f3153fceabc4) with tiling assistant and confirm works without issue.
