### ISSUE TITLE
Firefox does not stay tiled

### ISSUE THREAD

**Issue by Sirtz** [Leleat/Tiling-Assistant#139] opened 2022-01-22 12:38 UTC
**Describe the bug**
Firefox does not respect the tiling, as soon as another window is focused it snaps back to previous position before tile

**Steps To Reproduce**
Open Firefox
Tile left/right
Focus another window
Firefox will snap to a different position

**System Info:**
 - Distro (incl. version): Fedora 35
 - GNOME (Shell) version: 41.3
 - Extension version and from where: Up to date from gnome extentions
 - XOrg/Wayland: Wayland

**Journalctl logs**
"Error in size change accounting"

**Comment by Leleat** [comment] 2022-01-22 12:40
This is a duplicate of https://github.com/Leleat/Tiling-Assistant/issues/138 (and it's not limited to firefox).

Quoting myself from that issue:

> This is a mutter/gtk bug. Unfortunately, I don't think there is much I can do. All tiling extensions will be broken due to this. See https://gitlab.gnome.org/GNOME/mutter/-/issues/2091

Only workaround is to not use Wayland atm...

**Closed by Leleat** 2022-01-22 12:40 UTC
Labels: bug

**Comment by Sirtz** [comment] 2022-01-22 12:41
Ah thanks a lot. I was wondering if it was the same issue. Do you know why it works fine with brave but not firefox? And is there a fix on the horizon? Thank you a lot for this awesome extention!

**Comment by Leleat** [comment] 2022-01-22 12:46
This bug doesn't affect all windows. Checkout the mutter issue(s) for more info.

There is already a fix merged in gtk (for Gtk4). There is also an open MR in mutter to provide a workaround 'for all windows'. So hopefully the next GNOME release (41.4) should fix this issue.
