### ISSUE TITLE
Unable to focus on window after using 4 Quarters tiling mode

### ISSUE THREAD

**Issue by rbjorklin** [Leleat/Tiling-Assistant#276] opened 2023-07-05 16:20 UTC
**Describe the bug**
I am unable to focus on window after using 4 Quarters tiling mode. To be able to interact with the windows I have to drag them loose and put them back where they were.

**Steps To Reproduce**

**System Info:**
 - Distro (incl. version): Fedora 38
 - GNOME Shell version: gnome-shell-44.2-1.fc38.x86_64
 - Extension version and from where (e. g. EGO, `main` branch...): EGO, 41
 - XOrg/Wayland: Wayland

**Journalctl logs**

```
Error in size change accounting.
Old animationInfo removed from actor [0x5612fea01f70 MetaWindowActorWayland]
```

**Comment by Leleat** [comment] 2023-07-09 15:01
I am on the same system but I can't reproduce this.... Can you consistiently trigger the bug and does it require anything specific (i. e. steps-to-reproduce)?

**Comment by Numpienick** [comment] 2023-07-10 07:25
I have the same issue where my windows don't get repainted until I drag them. This happens almost every time for some/all of the windows when I press a shortcut to enable a layout.
Sometimes the window works, but it is super laggy, again until I drag the window.
Happens both on layouts that already set the apps and for layouts where I set the apps automatically.
It doesn´t seem to happen when I manually drag windows into a tile.

**System Info**:
    Distro (incl. version): Ubuntu 22.10
    GNOME Shell version: 43.1
    Extension version and from where (e. g. EGO, main branch...): Extension Manager. Version 41

**Comment by rbjorklin** [comment] 2023-07-10 18:41
I can trigger this consistently on a freshly started system. Not sure it's relevant but I have added a few applications to startup automatically, namely: [alacritty](https://github.com/alacritty/alacritty), slack, firefox and 1password.

**Comment by Leleat** [comment] 2023-07-16 15:50
> I can trigger this consistently on a freshly started system.

And how exactly do you trigger it? Do you use the layouts feature like Numpienick (for that I have an idea on how to fix it), do you just drag the windows to the screen edges, or do you use the keyboard shortcuts... i. e. what are your steps to reproduce it?

**Comment by rbjorklin** [comment] 2023-07-17 21:56
By clicking the `4 Quarters` button from the toolbar.
![Screenshot from 2023-07-17 14-55-54](https://github.com/Leleat/Tiling-Assistant/assets/1704798/c42e0f18-da20-4c7b-b40b-14bd0b3bf44e)

**Comment by rungitringit** [comment] 2023-09-12 22:34
I have had this problem with Ubuntu 22.04 and I often use quarters, however the problem is intermittent.

At one point yesterday I couldn't use the mouse to switch between windows, but had to alt+tab and then the mouse would work within a window.  I don't run any other extensions, so I'm afraid it was likely to be related.

**Comment by Leleat** [comment] 2024-02-20 15:40
This is probably the same issue as #304 so closing this one. A workaround is to disable the animations for Tiling Assistant preferences (after enabling the [advanced settings](https://github.com/Leleat/Tiling-Assistant/wiki/Advanced-and-Experimental-Settings)).

**Closed by Leleat** 2024-02-20 15:40 UTC
Labels: bug
