### ISSUE TITLE
Firefox 94 does not restore original size and position returning from fullscreen mode

### ISSUE THREAD

**Issue by saivert** [Leleat/Tiling-Assistant#113] opened 2021-11-04 15:25 UTC
**Describe the bug**
Since Firefox version 94, it seems it is no longer compatible with Tiling Extension and does not return to original size and position from fullscreen mode. This worked before. As soon as I disable Tiling Extension then it works as expected.

**Steps To Reproduce**
Open firefox version 49
Using Tiling Extension let it have the right side of the screen.
Launch YouTube video fullscreen,
Exit fullscreen mode.
Now Firefox is maximized instead of returning to original size and position. Gnome-shell also freezes a bit.

**System Info:**
 - Distro (incl. version): Fedora 34
 - GNOME (Shell) version: 40.5
 - Extension version: 27
 - XOrg/Wayland: Wayland

**Journalctl logs**

Getting lots of "Error in size change accounting" messages.

**List of other extensions**

Application Menu (stock extension)
AppIndicator and KStatusNotifierItem Support
Background Logo (stock extension)

**Screenshots/-captures**

**Comment by Leleat** [comment] 2021-11-04 16:11
Thanks, for the report. I can reproduce this and will look into it.

**Comment by Leleat** [comment] 2021-11-04 20:41
> This worked before. As soon as I disable Tiling Extension then it works as expected.

How exactly does it work? Do you use GNOME's native tiling and enter/leave the fullscreen?

Does it also work for normal floating firefox (i. e.  neither maximized nor tiled)?

**Comment by saivert** [comment] 2021-11-04 22:13
Looks like Firefox has a bug here on Wayland instead of Tiling Extension as floating Firefox windows behave the same even with Tiling Extension disabled.

**Comment by Leleat** [comment] 2021-11-04 22:26
> Looks like Firefox has a bug here on Wayland instead of Tiling Extension as floating Firefox windows behave the same even with Tiling Extension disabled.

In that case it's actually a GNOME Shell / mutter bug. See https://gitlab.gnome.org/GNOME/mutter/-/issues/1973

Coincidentally, *today* the commit, which caused the issue, has been reverted in the stable branches of GNOME Shell ([41.1](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/a3693715199948ee1479fd64b483fc39976eff69) and [40.6](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/aded2cd01b7af4d2bf355ed7cb129c6b869d84fb)), so once you get either version through your distro, it will work again.

So I am closing this since it's not my bug.

**Closed by Leleat** 2021-11-04 22:26 UTC
Labels: bug
