### ISSUE TITLE
[Multi-Monitor] When a window is dragged to the edge the primary screen, things start getting weird.

### ISSUE THREAD

**Issue by Camiropan** [Leleat/Tiling-Assistant#175] opened 2022-05-20 14:20 UTC
**Describe the bug** / **Steps To Reproduce**
I have two monitors in a horizontal arrangement, with the left monitor being the primary. 
When I drag a window to the left edge of the left monitor, the window takes up half the screen, as it should. 
However, when I select another application using the app picker, it shows in a strange position on the right monitor. 
Same scenario when a window is dragged to the right edge of the left monitor.
On the Right monitor, however, everything works as it should.

So when a window is dragged to the right side of my left screen, things start getting weird.

**System Info:**
 - Distro (incl. version): Fedora 36
 - GNOME (Shell) version: 42.1
 - Extension version and from where (e. g. EGO, `main` branch...): EGO, v33
 - XOrg/Wayland: Wayland

**Journalctl logs**
"Error in size change accounting."
But this message comes when the tiling works and when not.

**Comment by Leleat** [comment] 2022-05-20 15:17
Can you try the `main` branch and see if the issue still persists? Alternatively, please just apply [this commit](https://github.com/Leleat/Tiling-Assistant/commit/1e4176a9a7037ee5dd0612e4c9f9dbe45d4e67cf) and see if it fixes your issue. Don't forget to reload GNOME Shell after installing the new version/manually editing the file.

**Comment by szszoke** [comment] 2022-05-20 16:27
Thanks for the suggestion, I will give it a try and report back.

**Comment by Camiropan** [comment] 2022-05-20 18:05
Thank you for your fast answer!
I tried the main branch and it helps a lot. Unfortunately there are still two issues.

if an application is fullscreen (or even wider) and dragged to the right edge, its size does not change.

if an application isn't fullscreen (or wider) tiling works fine, but it seems that the window is maybe 2px wider than the screen, so it shows 2px on the right screen

**Comment by stanickovr** [comment] 2022-05-21 23:40
Not sure if this is helpful but I've also had weird bugs on primary screen, but after editing Gaps things started working as intended.

**Comment by Leleat** [comment] 2022-05-23 10:27
> Not sure if this is helpful but I've also had weird bugs on primary screen, but after editing Gaps things started working as intended.

Could you open a new issue please (with more details)? This sounds like a different issue.

**Comment by Leleat** [comment] 2022-05-23 12:15
> Not sure if this is helpful but I've also had weird bugs on primary screen, but after editing Gaps things started working as intended.

I've pushed a new commit. It fixes 'a' bug with the gaps. Don't know if it's the one you encountered... 

> if an application isn't fullscreen (or wider) tiling works fine, but it seems that the window is maybe 2px wider than the screen, so it shows 2px on the right screen

Can you (Camiropan) check out if this issue of yours was fixed with it as well?

**Comment by Camiropan** [comment] 2022-05-23 19:58
it helps. But when i resize two application (in 1:1 layout), these jumps in a 2:1 Layout.

**Comment by Leleat** [comment] 2022-05-23 20:12
> it helps. But when i resize two application (in 1:1 layout), these jumps in a 2:1 Layout.

Can you make a screencast? I don't really understand what you mean... Do you mean something like https://github.com/Leleat/Tiling-Assistant/issues/173 (there is a gif in that issue)

**Comment by Leleat** [comment] 2022-05-23 21:30
> it helps. But when i resize two application (in 1:1 layout), these jumps in a 2:1 Layout.

If I understood that issue correctly, it should be fixed in `main` now.

**Comment by Camiropan** [comment] 2022-05-23 21:53
Yep, its fixed! thanks

**Closed** 2022-05-23 21:53 UTC
Labels: bug

**Comment by Camiropan** [comment] 2022-05-23 22:05
There's still the problem with fullscreen

> if an application is fullscreen (or even wider) and dragged to the right edge, its size does not change.

so should i open a new issue?

**Comment by Leleat** [comment] 2022-05-23 22:14
> There's still the problem with fullscreen
>
>    if an application is fullscreen (or even wider) and dragged to the right edge, its size does not change.
>
> so should i open a new issue?

Please do. Also more information would be useful because I can't reproduce it. For instance the steps to reproduce (how do you drag a fullscreen window, also on a multi-monitor setup...).

**Comment by stanickovr** [comment] 2022-05-23 22:17
I can't reproduce the bug I've experienced ever since I changed the value for gaps...everything worked fine for me after the change.

**Comment by Leleat** [comment] 2022-05-23 22:28
> I can't reproduce the bug I've experienced ever since I changed the value for gaps...everything worked fine for me after the change.

In that case it's the same bug the latest commit fixes. The bug only occured if you never changed the gap settings before.
