### ISSUE TITLE
Resize does not work on Gnome 42 / XOgr / Ubuntu 22.04

### ISSUE THREAD

**Issue by dmalyuta** [Leleat/Tiling-Assistant#173] opened 2022-05-16 14:07 UTC
**Describe the bug**

Resizing windows once they are side-by-side tiled does not work. In most cases one of the windows disappears entirely off the screen and becomes very thin horizontally. More rarely, the division line jumps to make one of the very windows very thin, after which moving the cursor over the division line makes the resize work again (all while keeping the left mouse button pressed).

This occurs with all other Gnome extensions disabled.

**Steps To Reproduce**

Screen recording (sorry cannot see the mouse cursor, but I resize the windows by hovering the mouse over the division line and pressing the left mouse button): https://imgur.com/a/DqGAluh

**System Info:**
 - Distro (incl. version):  Ubuntu 22.04
 - GNOME (Shell) version: 42.0
 - Extension version and from where (e. g. EGO, `main` branch...): `main` branch
 - XOrg/Wayland: XOrg

**Journalctl logs**

```
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55921c9b4360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55921e96af30] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55921e96cde0] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55921c9b4360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55921e96af30] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55921e96cde0] is on because it needs an allocation.
Error in size change accounting.
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55921c9b4360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x559224890f10] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55921e96d4e0] is on because it needs an allocation.
Error in size change accounting.
No rect whose size to clamp to found!
No rect to clip to found!
No rect whose size to clamp to found!
No rect to clip to found!
No rect whose size to clamp to found!
No rect to clip to found!
No rect whose size to clamp to found!
No rect to clip to found!
No rect whose size to clamp to found!
No rect to clip to found!
Can't update stage views actor <unnamed>[<MetaWindowGroup>:0x55921c9b4360] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaWindowActorX11>:0x55921e96af30] is on because it needs an allocation.
Can't update stage views actor <unnamed>[<MetaSurfaceActorX11>:0x55921e96cde0] is on because it needs an allocation.
No rect whose size to clamp to found!
No rect to clip to found!
No rect whose size to clamp to found!
No rect to clip to found!
```

**Comment by Leleat** [comment] 2022-05-16 16:10
I can't seem to reproduce that even in an Ubuntu VM. Are you on the latest commit and does it happen with all windows? Can you post your extension settings here (`gsettings --schemadir ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas list-recursively org.gnome.shell.extensions.tiling-assistant`)

**Comment by dmalyuta** [comment] 2022-05-16 16:42
Thanks a lot for checking. I will post the extension settings tonight when I get back to my computer. Yes, ot does happen for all windows. Are you using XOrg rather than Wayland? I am using XOrg.

**Comment by Leleat** [comment] 2022-05-16 17:14
> Are you using XOrg rather than Wayland? I am using XOrg.

Yep, tried both in the VM (and am running XOrg on my Fedora machine).

**Comment by dmalyuta** [comment] 2022-05-17 05:55
Unfortunately with all the other Gnome extensions disabled, this issue still almost always happens. Any other system info that I can provide? I'm running stock Ubuntu 22.04 on a Dell XPS 13, configured by running the `install` script from the following project after OS installation: https://github.com/dmalyuta/dotfiles

Output of
```
gsettings --schemadir ~/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas list-recursively org.gnome.shell.extensions.tiling-assistant
```
is:
```
org.gnome.shell.extensions.tiling-assistant activate-layout0 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout1 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout10 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout11 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout12 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout13 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout14 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout15 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout16 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout17 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout18 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout19 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout2 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout3 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout4 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout5 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout6 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout7 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout8 @as []
org.gnome.shell.extensions.tiling-assistant activate-layout9 @as []
org.gnome.shell.extensions.tiling-assistant adapt-edge-tiling-to-favorite-layout false
org.gnome.shell.extensions.tiling-assistant auto-tile @as []
org.gnome.shell.extensions.tiling-assistant center-window @as []
org.gnome.shell.extensions.tiling-assistant changelog-version 33
org.gnome.shell.extensions.tiling-assistant debugging-free-rects @as []
org.gnome.shell.extensions.tiling-assistant debugging-show-tiled-rects @as []
org.gnome.shell.extensions.tiling-assistant default-move-mode 0
org.gnome.shell.extensions.tiling-assistant dynamic-keybinding-behaviour 0
org.gnome.shell.extensions.tiling-assistant enable-advanced-experimental-features false
org.gnome.shell.extensions.tiling-assistant enable-hold-maximize-inverse-landscape false
org.gnome.shell.extensions.tiling-assistant enable-hold-maximize-inverse-portrait false
org.gnome.shell.extensions.tiling-assistant enable-raise-tile-group true
org.gnome.shell.extensions.tiling-assistant enable-tile-animations true
org.gnome.shell.extensions.tiling-assistant enable-tiling-popup true
org.gnome.shell.extensions.tiling-assistant enable-untile-animations true
org.gnome.shell.extensions.tiling-assistant favorite-layout -1
org.gnome.shell.extensions.tiling-assistant favorite-layouts @as []
org.gnome.shell.extensions.tiling-assistant horizontal-preview-area 15
org.gnome.shell.extensions.tiling-assistant import-layout-examples false
org.gnome.shell.extensions.tiling-assistant maximize-with-gap false
org.gnome.shell.extensions.tiling-assistant move-adaptive-tiling-mod 0
org.gnome.shell.extensions.tiling-assistant move-favorite-layout-mod 3
org.gnome.shell.extensions.tiling-assistant restore-window ['<Super>Down']
org.gnome.shell.extensions.tiling-assistant restore-window-size-on 0
org.gnome.shell.extensions.tiling-assistant screen-bottom-gap -1
org.gnome.shell.extensions.tiling-assistant screen-left-gap -1
org.gnome.shell.extensions.tiling-assistant screen-right-gap -1
org.gnome.shell.extensions.tiling-assistant screen-top-gap -1
org.gnome.shell.extensions.tiling-assistant search-popup-layout @as []
org.gnome.shell.extensions.tiling-assistant show-changelog-on-update true
org.gnome.shell.extensions.tiling-assistant show-layout-panel-indicator false
org.gnome.shell.extensions.tiling-assistant tile-bottom-half ['<Super>KP_2']
org.gnome.shell.extensions.tiling-assistant tile-bottomleft-quarter ['<Super>KP_1']
org.gnome.shell.extensions.tiling-assistant tile-bottomright-quarter ['<Super>KP_3']
org.gnome.shell.extensions.tiling-assistant tile-edit-mode @as []
org.gnome.shell.extensions.tiling-assistant tile-left-half ['<Super>Left', '<Super>KP_4']
org.gnome.shell.extensions.tiling-assistant tile-maximize ['<Super>Up', '<Super>KP_5']
org.gnome.shell.extensions.tiling-assistant tile-maximize-horizontally @as []
org.gnome.shell.extensions.tiling-assistant tile-maximize-vertically @as []
org.gnome.shell.extensions.tiling-assistant tile-right-half ['<Super>Right', '<Super>KP_6']
org.gnome.shell.extensions.tiling-assistant tile-top-half ['<Super>KP_8']
org.gnome.shell.extensions.tiling-assistant tile-topleft-quarter ['<Super>KP_7']
org.gnome.shell.extensions.tiling-assistant tile-topright-quarter ['<Super>KP_9']
org.gnome.shell.extensions.tiling-assistant tilegroups-in-app-switcher false
org.gnome.shell.extensions.tiling-assistant tiling-popup-all-workspace false
org.gnome.shell.extensions.tiling-assistant toggle-always-on-top @as []
org.gnome.shell.extensions.tiling-assistant toggle-maximize-tophalf-timer 600
org.gnome.shell.extensions.tiling-assistant toggle-tiling-popup @as []
org.gnome.shell.extensions.tiling-assistant vertical-preview-area 15
org.gnome.shell.extensions.tiling-assistant window-gap 0
```

**Comment by dmalyuta** [comment] 2022-05-17 06:11
Update: something very strange indeed is going on. I installed the extension from code in the commit 465ae4fb1f63cbf33594d30f62da5260758e2547 and in this case window resizing works as expected. Moreover, Alt-dragging windows to the edge of the screen triggers tiling this time (which does not make sense since the fix for #172 only appears in the commit 8e0910351382a5942901b676a443e8048ed61c38 which comes after this one).

**Comment by Leleat** [comment] 2022-05-17 06:50
> Update: something very strange indeed is going on. I installed the extension from code in the commit https://github.com/Leleat/Tiling-Assistant/commit/465ae4fb1f63cbf33594d30f62da5260758e2547 and in this case window resizing works as expected. Moreover, Alt-dragging windows to the edge of the screen triggers tiling this time (which does not make sense since the fix for https://github.com/Leleat/Tiling-Assistant/issues/172 only appears in the commit https://github.com/Leleat/Tiling-Assistant/commit/8e0910351382a5942901b676a443e8048ed61c38 which comes after this one).

That's expected behaviour. Backstory as to why alt-dragging didn't previously work with the edges: I have different 'dragging modes' depending on which modifier is held during the drag. By default they are `Ctrl` and `Alt` (I didn't know that it was possible for `Alt` to be used for dragging windows). The fix for 172 added a check to see if the user has `Alt` set as the mouse move/resize modifier key and changes the Tiling Assistant's own mod key from `Alt` to `Super` so that `Alt` uses the normal edge tiling. As a result even if you go back in the git history the alt-dragging should work since the extension prefs aren't affected by that.

> Okay, I think I pinned it down. Window resizing is working fine on https://github.com/Leleat/Tiling-Assistant/commit/8e0910351382a5942901b676a443e8048ed61c38 but fails on the most recent commit https://github.com/Leleat/Tiling-Assistant/commit/1e4176a9a7037ee5dd0612e4c9f9dbe45d4e67cf (current HEAD of main branch). Something about that new logic is failing to succeed on my machine.

Hmm, that's weird. The latest commit only changed the function how a window is actually 'tiled'. Don't how that would be related to resizing... I'll try looking into it.

**Comment by dmalyuta** [comment] 2022-05-17 07:00
Thanks for the explanation. As for the fault, I don't know much about Gnome but prior to the commit the behaviour would have been:
```
window.move_resize_frame(false, x, y, width, height);
```
and now it is:
```
window.move_frame(true, x, y);
window.move_resize_frame(true, x, y, width, height);
```
I don't know what the `true` upfront means (previously is was `false`). In addition, I don't know what the effect of `move_frame` is.

**Comment by Leleat** [comment] 2022-05-17 09:40
> I don't know what the true in the first argument means (previously is was false). In addition, I don't know what the effect of move_frame is.

For context: `move_frame` simply moves the window. `move_resize_frame` moves *and* resizes the window. The first argument is a bool to indicate wether the move/resize operation is a user operation or not. If it is a user operation, the window won't be constrained to the monitor (imagine it like the user dragging a window outside the monitor). If it's false, the window will be constrainted to be within the monitor.

Previously I set the user_op to false because true caused GNOME (and some other) Terminal(s) to only resize but not move. However that seemed to cause issue 137. So I set it to true and tried to fix the terminal issue by first moving the window before calling `move_resize_frame`.

**Comment by dmalyuta** [comment] 2022-05-17 16:16
I tested and on my system the following work fine:
```
window.move_frame(false, x, y);
window.move_resize_frame(false, x, y, width, height);

// OR

window.move_resize_frame(false, x, y, width, height);

// OR

window.move_frame(true, x, y);
window.move_resize_frame(false, x, y, width, height);
```
These don't work:
```
window.move_frame(false, x, y);
window.move_resize_frame(true, x, y, width, height);

// OR

window.move_resize_frame(true, x, y, width, height);
```

My observation from this is that the fundamental problem is using `true`in the first argument of `window.move_resize_frame`. Something about that is broken, at least on my machine. Any chance you'd want to revert 1e4176a9a7037ee5dd0612e4c9f9dbe45d4e67cf or use `false`?

**Comment by Leleat** [comment] 2022-05-18 10:52
> Any chance you'd want to revert https://github.com/Leleat/Tiling-Assistant/commit/1e4176a9a7037ee5dd0612e4c9f9dbe45d4e67cf or use false?

I am probably just gonna add a toggle to the hidden settings. The default state will depend on wether other people also have this problem.

Btw, does the problem also happen if you only tile 1 window and try to resize it?

**Comment by Leleat** [comment] 2022-05-18 10:59
> Btw, does the problem also happen if you only tile 1 window and try to resize it?

If it does, can you

1. Open a window.
2. Open looking glass (`Alt`+`F2`, then enter `lg`)
3. Enter `global.display.get_tab_list(Meta.TabList.NORMAL_ALL, null)[0].move_resize_frame(true, 50, 50, 600, 600)`
4. Close looking glass with the Esc key
5. Try to resize the window

Does the issue still happen?

**Comment by Leleat** [comment] 2022-05-18 15:43
> The suggestion does not work unfortunately. The window gets resized by that command, but snapping it again to one side and resizing causes the same issue - even when it is not tiled with any other window. Here is a recording:
https://imgur.com/vKTRgKn

I meant to directly resize the window after the command (i. e. don't 'tile' it after the leaving looking glas). If the resizing problem still exists, then it is worth opening a bug report in GNOME.

**Comment by dmalyuta** [comment] 2022-05-18 15:57
There is no issue resizing the window after running that command, if I don't tile it after leaving the looking glass. The issue only happens when I resize a tiled window.

Where does one post GNOME bug reports? Do you think this is where this story ends - you'll keep the `true` argument, have a setting to use `false`, and I file a bug report with GNOME about the issue?

**Comment by dmalyuta** [comment] 2022-05-19 16:33
Glad that you are able to reproduce it, that'll make debugging easier for you. I found this discussion on the role of the `user_op` flag (the first argument of `move_frame` and `move_resize_frame`) enlightening: https://www.reddit.com/r/gnome/comments/kmoeh8/what_exactly_does_the_user_op_paramter_in/

Here is the source code for `move_resize_frame` that I was finally able to find after a lot of digging: https://github.com/GNOME/mutter/blob/c2b8582e0f49fbd5608deb51e9e1db50f13169f8/src/core/window.c#L4024

**Comment by Leleat** [comment] 2022-05-23 21:29
I think it should be fixed in `main` now.

**Closed** 2022-05-23 21:28 UTC
Labels: bug

**Comment by dmalyuta** [comment] 2022-05-25 05:42
Seems to work, yep! Was it setting the window default gap from -1 to 0 that fixed it, from 342e4baa9c8b2cc6db6084b8a7a92dae27afa02d ?

**Comment by Leleat** [comment] 2022-05-25 08:12
> Seems to work, yep! Was it setting the window default gap from -1 to 0 that fixed it, from https://github.com/Leleat/Tiling-Assistant/commit/342e4baa9c8b2cc6db6084b8a7a92dae27afa02d ?

Yes. When negative gaps were used (i. e. the default setting) the window would end up under the top bar. Trying to resize that window will end up causing the bug. This issue also happens outside of my extension. You can drag a window under the top bar, resize it and see the issue.

The reason why I couldn't reproduce it before was that I didn't use the default settings. If you changed the settings once, you could never go back to -1 because the spinbox is limited to 0 - 100.

**Comment by dmalyuta** [comment] 2022-05-25 08:32
Interesting! What do you mean by the "top bar"? Curious if you might have a GIF illustrating the issue "outside of your extension". I use the dash-to-panel extension so my GNOME actually does not have the classical top bar, as you can see in my GIFs.

**Comment by Leleat** [comment] 2022-05-25 08:36
I just meant that it also happens without my extension i. e. on vanilla GNOME. You don't really 'need' a top bar. Just move the window outside of the screen at the top and try to resize horizontally. The issue was reported in `mutter` here (there is also a video included): https://gitlab.gnome.org/GNOME/mutter/-/issues/1206

**Comment by dmalyuta** [comment] 2022-05-25 08:40
Great, thanks for explaining and for the fix!
