### ISSUE TITLE
Port to GNOME 42

### ISSUE THREAD

**Issue by shemgp** [Leleat/Tiling-Assistant#144] opened 2022-02-04 07:42 UTC
**Describe the bug**

Does not show tile window placeholder, nor does it tile any window.

**Steps To Reproduce**

1. Install GNOME 42~alpha for your distribution
2. Download 
3. Add version 42 to meta data
4. enable extension
5. Try to drag any to the side
6. See that it does not tile

**System Info:**
 - Distro (incl. version): Ubuntu Jammy Jellyfish (development version)
 - GNOME (Shell) version: 42.alpha
 - Extension version and from where (e. g. EGO, `main` branch...): master
 - XOrg/Wayland: XOrg

**Journalctl logs**

```
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Window manager warning: Overwriting existing binding of keysym 31 with keysym 31 (keycode a).
Window manager warning: Overwriting existing binding of keysym 32 with keysym 32 (keycode b).
Window manager warning: Overwriting existing binding of keysym 34 with keysym 34 (keycode d).
Window manager warning: Overwriting existing binding of keysym 35 with keysym 35 (keycode e).
Window manager warning: Overwriting existing binding of keysym 38 with keysym 38 (keycode 11).
Window manager warning: Overwriting existing binding of keysym 33 with keysym 33 (keycode c).
Window manager warning: Overwriting existing binding of keysym 36 with keysym 36 (keycode f).
Window manager warning: Overwriting existing binding of keysym 39 with keysym 39 (keycode 12).
Window manager warning: Overwriting existing binding of keysym 37 with keysym 37 (keycode 10).
```

**Comment by Leleat** [comment] 2022-02-04 11:17
I tested T-A in a VM and already fixed some issues (locally); for example like the dragging a window to the screen edges. But there is some other stuff that is quite badly broken atm e. g. there is no way to close the Tiling Popup so you end up in an 'infinite loop' if you use that feature... That's why I highly recommend you disable T-A while I haven't officially supported GNOME 42 yet. 

I'll start porting to GNOME 42 once the new Fedora Beta is released (because developing/testing my extension in a VM isn't a great experience). So it should be sometime in march.

**Comment by baco** [comment] 2022-03-07 15:16
@Leleat it seems the release date has been delayed to April. Does it have to be that long? In many distros GNOME 42.beta has been around for a month now.

Perhaps, as an alternative, instead of developing in a VM, developing directly to the image, buy booted from a pendrive in the real computer?

**Comment by styeff** [comment] 2022-03-12 16:52
I had this error here, after running build.sh, copying files to extension folder and renaming it. I modified metatada.json adding "42", but i still get errors. 

The settings of extension tiling-assistant@leleat-on-github had an error:
```
Error: set_titlebar() is not supported for Adw.Window
```

Stack trace:
```
set_titlebar/<@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:51:17
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:21:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by Jedsek** [comment] 2022-04-03 04:00
@Leleat Hello, the new Fedora Beta with gnome42 has been released.   
https://getfedora.org/en/workstation/download/

**Comment by pabs3** [comment] 2022-04-05 04:27
FYI gnome-shell 42 has reached Debian bookworm and so gnome-shell-extension-tiling-assistant has been removed from Debian bookworm:

https://bugs.debian.org/1008558

**Comment by sej7278** [comment] 2022-04-08 12:43
the extension doesn't even work on debian sid (when installed from here/e.g.o) even if you add 42 to the metadata, i didn't even know you could get it from apt!

**Comment by starise** [comment] 2022-04-08 21:07
Just did `yay -Syu` on ArchLinux and now I'm on Gnome 42. I saw Leleat is working on an update, thanks for your work, hope it will come soon. :+1:

**Comment by Leleat** [comment] 2022-04-26 11:54
I've pushed new commits to `main`. It should add support for GNOME 42. Please test it, if you can and report issues here. After some testing I'll upload it to EGO.

**Comment by sej7278** [comment] 2022-04-26 14:11
Testing on debian sid now, can't believe how much i've missed this!

**Comment by imtheleviathan** [comment] 2022-04-26 20:14
> 
Working on Arch!

**Comment by imtheleviathan** [comment] 2022-04-26 20:14
Working on Arch!

**Comment by danielcherubini** [comment] 2022-04-26 21:15
Working on arch

**Comment by brousselle** [comment] 2022-04-27 08:31
heard about this extension after upgrading to ubuntu 22.04.
I tested it this morning.
It seems to work as expected, but i am not yet an expert on all features of this extension.
I already love it !

**Comment by baco** [comment] 2022-04-27 12:34
I've tested the current development version on Debian since yesterday, it works, with just one glitch I think is from the extension itself. If I tile two windows, resize the panels (say I move the in between separation 10px to the left), then restore one of the windows to its original size and position, and try to retile a window in the remaining space; the newly tiled window does not fit the entire gap, only half of the screen:
![image](https://user-images.githubusercontent.com/102958/165518277-bc2fd3b6-28ae-4ab7-ad37-086707f6f889.png)

Here, I've tiled Tiling Assistant settings window to the left, then a terminal to the right, after that I've resize the panes moving the in-between separation some space to the left (shrinking the setting window and stretching the terminal one), then restored the terminal window and re-tiled it to the right.

My expected behavior would have been to fit the same space it left free when restoring.

**Comment by Leleat** [comment] 2022-04-27 14:01
> @baco if i understand what you're doing correctly i can reproduce but think its expected behaviour.

Actually it should be a bug. I expect the Terminal in baco's example to fill the remaining 2/3. Here is a recording of me doing it (in a Fedora Rawhide VM)

https://user-images.githubusercontent.com/53054301/165535729-727357bd-409f-4af9-9c29-43671f6b8f49.mov

Only cases where the Terminal shouldn't take the 2/3 are
1. if a different window already takes that 2/3 spot or
2. if a different window overlaps the extensions preference (see the second half of my video)
Unfortunately, as I've shown I can't reproduce this bug... I'll try some more. If I fail to reproduce it, I'll come back to query for some more info.

**Comment by baco** [comment] 2022-04-27 15:06
Here is my video, without having to add a third window to reproduce the behavior. It happens what Leleat showed but with the just 2 windows:

https://user-images.githubusercontent.com/102958/165549975-ac4de6cc-a713-46c4-8510-643c979e718f.mp4

@sej7278 FWIW, it was never a GNOME Terminal, in my first screenshot was Kitty Terminal, and in the screencast is GNOME Console which is intended to be the GTK4 GNOME Terminal replacement.

```
baco@terrapin ~> apt policy gnome-shell
gnome-shell:
  Installed: 42.0-4
  Candidate: 42.0-4
  Version table:
 *** 42.0-4 990
        990 http://deb.debian.org/debian testing/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by Leleat** [comment] 2022-04-27 15:19
I can reproduce it in GNOME OS. So I'll try to fix it.

**Comment by barreiroleo** [comment] 2022-04-28 22:15
Working on Arch. Gnome 42.1 with X11 and Wayland.

**Comment by dclay1983** [comment] 2022-04-30 02:40
Working on Pop OS 22.04 Gnome 42. The install script didn't work correctly though. I had to manually move the extension directory and compile the schema myself. Not hard to figure out and probably a better option anyways. I didn't get an error output from the script btw, it said it was successful. 2 restarts later, I knew better.

**Comment by Leleat** [comment] 2022-04-30 18:02
> Actually it should be a bug. I expect the Terminal in baco's example to fill the remaining 2/3. Here is a recording of me doing it (in a Fedora Rawhide VM)

Fixed the issue.

> Working on Pop OS 22.04 Gnome 42. The install script didn't work correctly though. I had to manually move the extension directory and compile the schema myself. Not hard to figure out and probably a better option anyways. I didn't get an error output from the script btw, it said it was successful. 2 restarts later, I knew better.

I installed PopOS 22.04 in a VM and don't think I can reproduce it. The first install attempt exited with an error because `gettext` wasn't installed. After installing `gettext` the script worked for me and the extension was installed after restarting GNOME Shell. Did you perhaps run the build script without the `-i` option?

**Comment by shdwchn10** [comment] 2022-05-05 13:15
Hello! There is a [Go/No-Go meeting](https://lists.fedoraproject.org/archives/list/test-announce@lists.fedoraproject.org/thread/2E2LYF3EX53SZ2YC6ADCRCZXLDJPWPFF/) scheduled today for Fedora Linux 36. It's highly likely that a decision will be made to release on May 10th. It would be cool to have a Tiling Assistant release with GNOME 42 support on EGO by then!

**Comment by Leleat** [comment] 2022-05-06 12:46
>Hello! There is a [Go/No-Go meeting](https://lists.fedoraproject.org/archives/list/test-announce@lists.fedoraproject.org/thread/2E2LYF3EX53SZ2YC6ADCRCZXLDJPWPFF/) scheduled today for Fedora Linux 36. It's highly likely that a decision will be made to release on May 10th. It would be cool to have a Tiling Assistant release with GNOME 42 support on EGO by then!
>
>Thank you for your extension and great work!
>
>UPD: Yes, it's [GO now](https://lists.fedoraproject.org/archives/list/test-announce@lists.fedoraproject.org/thread/YOSGMJ5C6OLCXPOKBGVMAJSANKZLQEZT/) and will be released on May 10th

I'll test some multi-monitor stuff on the weekend and if I don't notice any new issues I'll make a new release.

**Comment by danielcherubini** [comment] 2022-05-06 13:26
If it helps any. I have been testing with three monitors and one of which is vertical. 

It all works great. 

Only thing is on the vertical monitor if the top bottom half split could be a little easier when dragging with the mouse. 

Currently it requires me to drag it into the corner, then slowly drag it out from the corner towards the centre of the top/bottom. If I go too far I miss the spot and it's thinking I want the whole screen.

**Comment by Leleat** [comment] 2022-05-07 15:34
Alright, made a new release and uploaded it to EGO now. Just waiting for the review. So closing this issue. Thanks to everyone who tested the `main` branch.

> Only thing is on the vertical monitor if the top bottom half split could be a little easier when dragging with the mouse.
>
> Currently it requires me to drag it into the corner, then slowly drag it out from the corner towards the centre of the top/bottom. If I go too far I miss the spot and it's thinking I want the whole screen.

Could you open a new issue for your problem? A short screencast would be helpful because I am not sure if you are talking about the timer that exists to switch between the 'Maximize' tiling and the 'Top half' tiling (which wouldn't be a bug).

**Closed by Leleat** 2022-05-07 15:34 UTC
Labels: bug
