### ISSUE TITLE
Tiled window untiles if a different window is focused

### ISSUE THREAD

**Issue by Marathon2112** [Leleat/Tiling-Assistant#138] opened 2022-01-14 20:35 UTC
**Describe the bug**
Tiled windows resize when focus is switched to another window.

**Steps To Reproduce**

1. Open a couple windows.
2. Tile one window.
3. Click on the other window to bring it into focus. The tiled window gets resized (see screen cast).

**System Info:**
 - Distro (incl. version): `Arch Linux x86_64`
 - GNOME (Shell) version: `GNOME 41.3`
 - XOrg/Wayland: `Wayland`

**Journalctl logs**
```
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
Error in size change accounting.
```
(One line gets added every time the window is tiled or the focus is changed.)

**List of other extensions**

```
auto-move-windows@gnome-shell-extensions.gcampax.github.com
tiling-assistant@leleat-on-github
arch-update@RaphaelRochet
blur-my-shell@aunetx
gtktitlebar@velitasali.github.io
```

**Screenshots/-captures**

https://user-images.githubusercontent.com/38672550/149581598-2c3bf5de-5dfc-4e6d-afeb-69e5735ebdeb.mp4

**Comment by Leleat** [comment] 2022-01-14 22:44
> Error in size change accounting.

This error occurs because I use GNOME's animation system for un/tiling animations. They weren't meant for extensions but I don't think I am gonna change it because it doesn't appear to introduce any functional bugs. You can get rid of these warnings by disabling the un/tiling animations in TA's [hidden preferences](https://github.com/Leleat/Tiling-Assistant/blob/main/GUIDE.md#Hidden-Settings).

The other error I've never seen before. Not sure, if it's related...

- I am also on GNOME Shell 41.3 and can't reproduce this. Which extensions version are you using (the one from EGO or AUR, `main`...)?
- Can you disable all other extensions, reload GNOME Shell (log out and back in) and see if the problem still exists?

**Comment by Leleat** [comment] 2022-01-15 02:20
This is a `mutter` bug. Unfortunately, I don't think there is much I can do. All tiling extensions will be broken due to this. See https://gitlab.gnome.org/GNOME/mutter/-/issues/2091

**Comment by Alex-Bujorianu** [comment] 2022-02-23 19:15
I am able to reproduce this bug as well. Until it gets fixed, Tiling Assistant is not usable on Wayland.

**Comment by piotrzientarski** [comment] 2022-02-23 19:18
This was fixed in GNOME 41.4

**Comment by Alex-Bujorianu** [comment] 2022-02-23 19:30
I see @piotrzientarski. Gnome 41.4 is not available on Manjaro stable yet.

**Comment by Leleat** [comment] 2022-04-26 12:11
Closing this as I think this has been fixed upstream.

**Closed by Leleat** 2022-04-26 12:11 UTC
Labels: Wayland, Not *my* bug
