### ISSUE TITLE
Ubuntu 24.04: Orange rectangle fills screen during tiling action

### ISSUE THREAD

**Issue by GerryT11** [Leleat/Tiling-Assistant#345] opened 2024-05-20 13:43 UTC
**Describe the bug**
Sometimes, when I put a window in a tile, an orange rectangle fills screen during tiling action and does not disappear. 
I have to try several times to "rip off" the window from the position, then the orange rectangle goes away.

The bug is also described here by other people:
https://askubuntu.com/questions/1512152/what-is-this-orange-thing-taking-up-half-of-my-screen
https://askubuntu.com/questions/1511871/ubuntu-24-04-possible-bug

Is this a know bug?

**Steps To Reproduce**
It appears sometimes, I don't exactly know when.

**System Info:**
 - Ubuntu 24.04
 - GNOME Shell version: 46 (which is in Ubuntu 24.04)
 - Extension version and from where (e. g. EGO, `main` branch...): Automatically installed with Ubuntu 24.04
 - XOrg/Wayland: Wayland

**Comment by Leleat** [comment] 2024-05-20 14:22
> Is this a know bug?

Not to me at least. That said, I don't use Ubuntu. So it's kinda hard to fix without clear steps-to-reproduce. I'll try and see if I can reproduce this behavior in an Ubuntu VM.

In the meantime, if you encounter this bug, please check the the `journalctl` logs and see if you can see anything that looks related to the tiling extension. `journalctl -f /usr/bin/gnome-shell` will 'follow' the the journal live. `journalctl -r /usr/bin/gnome-shell` will show you the log in 'reverse'.

**Comment by dkrizan** [comment] 2024-05-22 09:07
> Also, can you please tell me more about your setup. Are you using multiple monitors? Are you using a touchpad? Does it only happen with specific apps/windows etc...
> 
> And what are the settings of the extension? The settings can be gotten with the following command: `gsettings list-recursively org.gnome.shell.extensions.tiling-assistant`
> 
> [Edit]
> 
> And what other extensions do you use (`gnome-extensions list --enabled`)?

I am having similar issue, but in my case whenever I click on top panel (the one with date and time in center), the active window is resized to smaller size and half of the screen is filled with orange rectangle (same rectangle which is shown when you want to snap the window to any of the side of display).

Does not matter if I use primary display only or multiple displays.

**System info:**
- Ubuntu 24.04
- GNOME Shell 46.0
- extension version 46 (included in Ubuntu 24.04)
- Wayland

Enabled extensions (`gnome-extensions list --enabled`)
```
ding@rastersoft.com
tiling-assistant@ubuntu.com
ubuntu-appindicators@ubuntu.com
ubuntu-dock@ubuntu.com
```

**Comment by Leleat** [comment] 2024-05-26 15:56
Weird, I've got an email a few days ago about a new reply here. I can't see it though (tested on multiple devices). I don't think the comment was deleted as I believe there would be a placeholder... so I am just gonna copy-paste the comment here but I am gonna omit the name:

> I am having similar issue, but in my case whenever I click on top panel (the one with date and time in center), the active window is resized to smaller size and half of the screen is filled with orange rectangle (same rectangle which is shown when you want to snap the window to any of the side of display).
> 
> Does not matter if I use primary display only or multiple displays.
> 
> System info:
> 
>     Ubuntu 24.04
>     GNOME Shell 46.0
>     extension version 46 (included in Ubuntu 24.04)
>     Wayland
> 
> Enabled extensions (gnome-extensions list --enabled)
> 
> ding@rastersoft.com
> tiling-assistant@ubuntu.com
> ubuntu-appindicators@ubuntu.com
> ubuntu-dock@ubuntu.com

---

And my reply to that:

> I am having similar issue, but in my case whenever I click on top panel (the one with date and time in center), the active window is resized to smaller size and half of the screen is filled with orange rectangle

That is fixed in Tiling Assistant v47. That release didn't make it into Ubuntu yet as the release of that version was probably too close to Ubuntu's release... I don't know how long it takes or how their packaging/updating process works as I am not involved with the downstream extension.

If someone from Ubuntu's team can tell me how the packaging/update process works or what kind of deadline I need to keep in mind to get T-A releases into ubuntu, then I'll pay attention to it and make releases earlier.

---
Going back to the actual bug... I was able to reproduce it with the top panel click and when trying to minimize windows. Both appear to be fixed in v47 of Tiling Assistant, so it seems that they have the same underlying cause (which is fixed in the latest T-A release). If you have other situations, where the preview rectangle stays around, please test the latest T-A version and see if it goes away. If you want to try out T-A, you need to disable Ubuntu's Tiling Assistant first __and logout__. Otherwise you probably run into issues during the installation of T-A because of namespacing issues.

**Comment by dkrizan** [comment] 2024-05-26 16:37
> Weird, I've got an email a few days ago about a new reply here. I can't see it though (tested on multiple devices). I don't think the comment was deleted as I believe there would be a placeholder... so I am just gonna copy-paste the comment here but I am gonna omit the name:
> 
> > I am having similar issue, but in my case whenever I click on top panel (the one with date and time in center), the active window is resized to smaller size and half of the screen is filled with orange rectangle (same rectangle which is shown when you want to snap the window to any of the side of display).
> > Does not matter if I use primary display only or multiple displays.
> > System info:
> > ```
> > Ubuntu 24.04
> > GNOME Shell 46.0
> > extension version 46 (included in Ubuntu 24.04)
> > Wayland
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Enabled extensions (gnome-extensions list --enabled)
> > [ding@rastersoft.com](mailto:ding@rastersoft.com)
> > [tiling-assistant@ubuntu.com](mailto:tiling-assistant@ubuntu.com)
> > [ubuntu-appindicators@ubuntu.com](mailto:ubuntu-appindicators@ubuntu.com)
> > [ubuntu-dock@ubuntu.com](mailto:ubuntu-dock@ubuntu.com)
> 
> And my reply to that:
> 
> > I am having similar issue, but in my case whenever I click on top panel (the one with date and time in center), the active window is resized to smaller size and half of the screen is filled with orange rectangle
> 
> That is fixed in Tiling Assistant v47. That release didn't make it into Ubuntu yet as the release of that version was probably too close to Ubuntu's release... I don't know how long it takes or how their packaging/updating process works as I am not involved with the downstream extension.
> 
> If someone from Ubuntu's team can tell me how the packaging/update process works or what kind of deadline I need to keep in mind to get T-A releases into ubuntu, then I'll pay attention to it and make releases earlier.
> 
> Going back to the actual bug... I was able to reproduce it with the top panel click and when trying to minimize windows. Both appear to be fixed in v47 of Tiling Assistant, so it seems that they have the same underlying cause (which is fixed in the latest T-A release). If you have other situations, where the preview rectangle stays around on Ubuntu 24.04, please test the latest T-A version and see if it goes away*. If it does, that means you just need to wait for an Ubuntu update carrying the new T-A version (v47 of T-A, not GNOME 47).
> 
> * If you want to try out T-A, you need to disable Ubuntu's Tiling Assistant first **and logout**. Otherwise you probably run into issues during the installation of T-A because of namespacing issues.

 It was my comment, which i deleted after a few minutes, as I found out what you mentioned - that it was fixed in the latest release.

**Comment by Leleat** [comment] 2024-05-26 17:01
> It was my comment, which i deleted after a few minutes, as I found out what you mentioned - that it was fixed in the latest release.

Ah, I see. I didn't expect Github to actually completely remove a comment without any indication of it ever being there... weird, but okay. Thanks for the headsup.

**Comment by Leleat** [comment] 2024-06-14 13:17
> could you share the reference to the commit which resolved the problem?

[This PR](https://github.com/Leleat/Tiling-Assistant/pull/328) fixes this particular issue.

> I'm working on cherrypicking some fixes for Ubuntu, including the one for this issue (our stable update rules are quite strict sowe can't simply use v47 since it contains some changes which aren't bugfixes)

Since you (someone from the Ubuntu team) are already here, let me ask you some questions 🙂. I am totally up for making it easier to work with Tiling Assistant. 

I just use the `main` branch without any kind of versioning scheme for development... which, I guess, kinda makes it hard for cherry-picking when there are also features and refactorings happening (the later is what I am doing quite a bit ATM). 

Would it be helpful, if I start versioning with branches? E. g. create a branch for v46 of Tiling Assistant where I backport/cherry-pick bugfixes so that you can more easily cherry-pick stuff for your downstream extension? If yes, what are the rules for the Ubuntu releases? Are minor versions (according to semantic versioning) allowed or only patches?

How long before an Ubuntu release should I merge stuff to get it into the next version. This would be helpful to know so that I can priotize things.

Lastly, if there is anything else that I can improve to make it easier for you, let me know.

**Comment by seb128** [comment] 2024-06-14 15:26
> [This PR](https://github.com/Leleat/Tiling-Assistant/pull/328) fixes this particular issue.

Thanks for the PR reference, I already started cherrypicking this one to fix the report we had about 'click on the top panel sometime trigger a tiling action', nice to see it also fixes the current problem :-)

> Since you (someone from the Ubuntu team) are already here, let me ask you some questions 🙂. I am totally up for making it easier to work with Tiling Assistant.

Great to read! :-)

> Would it be helpful, if I start versioning with branches? E. g. create a branch for v46 of Tiling Assistant where I backport/cherry-pick bugfixes so that you can more easily cherry-pick stuff for your downstream extension? If yes, what are the rules for the Ubuntu releases? Are minor versions (according to semantic versioning) allowed or only patches?

Yes, having a 'stable' branch with only fixes would make things easier on our side and probably also benefit some other distributions which have similar rules for stable update.

The Ubuntu SRU guidelines allows to SRU new versions if they only includes bugfixes/changes compatible with our SRU guidelines
https://wiki.ubuntu.com/StableReleaseUpdates#New_upstream_microreleases

> How long before an Ubuntu release should I merge stuff to get it into the next version. This would be helpful to know so that I can priotize things.

You can find the Ubuntu schedule on our discourse. Example for the current Oracular cycle
https://discourse.ubuntu.com/t/oracular-oriole-release-schedule

Which roughly align with the GNOME upstream schedule
https://release.gnome.org/calendar/

The important milestones there from our perspective (which is similar to GNOME's one) are Feature Freeze, UI Freeze and String Freeze.

> Lastly, if there is anything else that I can improve to make it easier for you, let me know.

Nothing special that I can think of but thanks for asking. Having stable bugfixes releases (similar to what GNOME is doing) would already be great.

Also if you have any issue reported by Ubuntu users or things to ask us or point out feel free to tag me on the github, or to reach out on #ubuntu-desktop(IRC) / #desktop(matrix) / https://bugs.launchpad.net/ubuntu/+source/gnome-shell-extension-tiling-assistant

We will also try to be good downstream contributors and forward issues and patches to the upstream project when we can.

**Comment by Leleat** [comment] 2024-07-21 11:53
Closing this as this seems to have also landed in Ubuntu.

**Closed by Leleat** 2024-07-21 11:53 UTC
Labels: bug, Fixed
