### ISSUE TITLE
'Edge Tiling Plus' Proposal

### ISSUE THREAD

**Issue by Daniel-Blandford** [Leleat/Tiling-Assistant#315] opened 2023-12-27 12:39 UTC
**Briefly describe how the feature should work**
Edge Tiling Plus: Simply put, taking the quad corner layout and detecting when a corner window is closed and filling the rest of the vertical space with the other window on that side.
i.e. on the right side of the display I have two windows one in the top corner and one in the bottom corner. Upon closing the bottom corner window, the current top corner window would fill the entire right side of the display and appear the same as it would had I taken that window and simply snapped it to take up the entire right side of the display.

**Explain why this feature should be added**
I'm not looking for anything overly complicated as a tiling window manager that automates everything, I simply like the addition of the quad corner snapping (and the slight window padding, but thats another conversation lol) as my experiences of using tiling window managers was of just sheer annoyance when they were automating cycles that I didn't want automated. I like using Gnome as I like the whole concept of keeping things simple and this extension with Edge Tiling adds a nice simple feature of quad snapping without over complicating the experience, but I think that the one minor addition to fill the vertical space when a window is closed and halving the vertical window space used by a window when another gets snapped into a quad zone corner that would lead to drawing over the window behind it (particularly regarding left/right window snapping zones) would give me some of the positives of tiling window managers without it reaching that point that it just becomes a sheer nuicance.

As strange as this might sound, I like the left and right zones of my screens to be independent of each other, so I wouldn't quite want to see this lead to left/right windows being closed causing another window to go full screen as all too often apps and websites have dead horizontal whitespace and so I don't want to just casually give those applications more horizontal space.
![ezgif com-animated-gif-maker](https://github.com/Leleat/Tiling-Assistant/assets/84602475/6a4c6802-80f1-416a-b5fe-542ecc635a57)

**Comment by Leleat** [comment] 2024-04-07 11:08
Tiling Assistant did have this feature way back in its earlier days... or maybe I was just experimenting with it, I don't remember exactly. But I ended up removing/not implementing it. IIRC, the main reasons were inconsistency, unpredictability, and the fact that it may be too opinionated in ambiguous cases.

E. g. let's say you have 4 windows tiled in quarters and you close 1 of them. Now the problem is which window should you expand? You could choose to _always_ expand a window vertically like you suggested (or horizontally or based on the monitor orientation). The problem is there may be multiple windows that could be expanded in that direction, if the layout is more complex than just 4 quarters. Another option is to expand the closest MRU window. But that may be a bit unpredictable. Ofc, Tiling Assistant could to do nothing in ambiguous cases. But that may confuse users why sometimes a window expands and sometimes it doesn't. This feature would probably require multiple settings to make users happy. And I am not willing to add that for this niche of a feature. So I am closing this.

**Closed by Leleat** 2024-04-07 11:08 UTC
Labels: enhancement
