### ISSUE TITLE
When tiling flatpak apps, pressing the right tile key(Meta+Right Arrow/Numpad 6) twice freezes the flatpak window.

### ISSUE THREAD

**Issue by Anvith00** [Leleat/Tiling-Assistant#264] opened 2023-05-12 20:11 UTC
### **Bug:**
Not sure if this is in any form related exclusively to XWayland or Wayland, but when I tile flatpak apps to the right side and press the right tile key (same direction) again, it freezes the entire flatpak window, unless I use the tile key in the opposite direction to undo the contents inside the window from freezing. Video is affected, audio isn't.

**This particular issue cannot be captured on a video recording unfortunately**.

`nvtop` and `gnome-system-monitor` shows no anomalies with CPU or GPU (such as CPU peaking to 100 percent usage, or GPU not being used at all). The left half of the window with the flatpak/non-flatpak app still works fine and has no such issue.

### **Steps To Reproduce:**
1. Tile a flatpak window to its empty half to the right side (Meta+RightArrow/Numpad 6).
2. Press the same tiling key again (Meta+RightArrow/Numpad 6).
3. The content inside the flatpak window  on the right halffreezes.

 
### **System Info:**
 - Distro (incl. version): Fedora Workstation 38
 - GNOME Shell version: GNOME Shell 44.1
 - Extension version and from where (e. g. EGO, `main` branch...): Version 40, from [Extension Manager](https://flathub.org/apps/com.mattjakeman.ExtensionManager).
 - Session: Wayland. Affects both Wayland and XWayland flatpak apps.

### **Journalctl logs:**

> Error in size change accounting.
> Error in size change accounting.
> Old animationInfo removed from actor [0x5578651c1db0 MetaWindowActorX11]
> Error in size change accounting.
> Error in size change accounting.
> meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
> meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed
> clutter_actor_get_preferred_width: assertion 'CLUTTER_IS_ACTOR (self)' failed
> clutter_actor_get_preferred_height: assertion 'CLUTTER_IS_ACTOR (self)' failed
> Window manager warning: META_CURRENT_TIME used to choose focus window; focus window may not be correct.
> Old animationInfo removed from actor [0x55785feda760 MetaWindowActorX11]
> Error in size change accounting.
> Error in size change accounting.
> Error in size change accounting.
> Error in size change accounting.
> Old animationInfo removed from actor [0x55785feda760 MetaWindowActorX11]
> Error in size change accounting.
> Old animationInfo removed from actor [0x55785feda760 MetaWindowActorX11]
> Error in size change accounting.
> Old animationInfo removed from actor [0x55785feda760 MetaWindowActorX11]
> Error in size change accounting.
> Error in size change accounting.
> Error in size change accounting.
> Old animationInfo removed from actor [0x55785feda760 MetaWindowActorX11]
> Error in size change accounting.
> Old animationInfo removed from actor [0x55785feda760 MetaWindowActorX11]
> Error in size change accounting.
> Error in size change accounting.
> Error in size change accounting.
> Error in size change accounting.
> Error in size change accounting.
> Old animationInfo removed from actor [0x55785feda760 MetaWindowActorX11]
> Error in size change accounting.
>

**Comment by Leleat** [comment] 2023-05-13 19:53
I can't reproduce this with the same setup (Fedora 38, Wayland, XWayland/Wayland apps/flatpaks). Does it also happen with Tiling Assistant disabled? For instance, there were recently https://gitlab.gnome.org/GNOME/mutter/-/issues/2805 and https://gitlab.gnome.org/GNOME/mutter/-/issues/2805

**Comment by Anvith00** [comment] 2023-05-16 10:21
Greetings @Leleat, I apologise for the late reply.

No, it does not occur with Tiling Assistant disabled. But I certainly suspect a mutter bug, because I recently switched to Ubuntu (kernel 5.19 and an older mutter version) and the issue was not present. In fact, the current Fedora release has had graphical bugs with mutter (I have an Intel Iris Xe Tigerlake GPU) that have been affecting my workflow (black window borders, random stutters, etc.)

**Comment by Leleat** [comment] 2023-05-17 18:01
Maybe you can open an issue on mutter and get help there... but yeah, I don't think it's directly a bug of Tiling Assistant i. e. I don't think it's something I can actually fix. So closing this.

**Closed by Leleat** 2023-05-17 18:01 UTC
Labels: bug
