### ISSUE TITLE
Support for GNOME 42

### ISSUE THREAD

**Issue by arushsharma24** [Leleat/Tiling-Assistant#153] opened 2022-04-08 05:19 UTC
Hey, so GNOME 42 is here and this extension isn't supported in it, so it would be amazing if someone could bump it up.
I tried adding the version "42" in the metadata.json file but it ended up giving me the an error of:-

``` GLib.FileError: Failed to open file “/home/kira/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/schemas/gschemas.compiled”: open() failed: No such file or directory ```

I'm not sure if this is some buggy error or due to some change in the GNOME 42 code as compared to previous GNOME versions (which I doubt since in that case I suppose it would affect a lot of extensions". Anyways, if someone could guide me on how I can fix this or maybe fix it themselves that would be great!

Love this extension! Thanks!

**Comment by furai** [comment] 2022-04-08 07:12
Duplicate of #144?

**Comment by Leleat** [comment] 2022-04-08 09:04
> Duplicate of https://github.com/Leleat/Tiling-Assistant/issues/144?

Indeed, thanks.

**Closed by Leleat** 2022-04-08 09:04 UTC
